# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55c4983368a644463e500ddf187a400b1a970707813686ed1e33f5301ea5f40ed1770eae679589f1f906cee7373663df243409dd8e4cfca1a6079edf7dbee321

test:
  secret_key_base: b62e922f4fe976ab35f3ae8e671d41eb6481bfa48099dfaeed98ce7ad9c70c34a6b9144aa57873f3f1c9b8ec2469c7162cdb6b488f755ae28f9a1671c5da83d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
